# **1. Conectar Google Drive a Colab (Mounting)**

Nuestro paso cero obligatorio para autorizar a Colab a buscar archivos en la nube:
* `from google.colab import drive`: Llamamos a la herramienta de conexión.
* `drive.mount('/content/drive')`: Abrimos el puente hacia nuestro almacenamiento virtual.

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **2. Cargar el archivo de Excel**

Importamos las herramientas necesarias y abrimos nuestra base de datos:
* `import pandas as pd`: Llamamos a la librería Pandas.
* `read_excel()`: Cargamos el archivo de la NBA usando su ruta exacta en el Drive.

In [5]:
import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/aplicada/Nba Teams.xlsx')

# **3. Aislar la columna de salarios**

Antes de hacer matemáticas, recordamos cómo extraer una sola variable:
* `nba["Salary"]`: Extraemos únicamente la columna que contiene los salarios de los jugadores para poder aplicarle operaciones numéricas.

In [6]:
nba["Salary"]

0      18000000.0
1       1701593.0
2       1517981.0
3             NaN
4      16000000.0
          ...
493     4692840.0
494           NaN
495    41358814.0
496     8333333.0
497     3372840.0
Name: Salary, Length: 498, dtype: float64

# **4. Operaciones de Suma (Suma masiva)**

Podemos sumar un valor fijo a todos los registros de la columna al mismo tiempo. Existen dos formas de hacerlo:
* `.add(50000)`: El método formal de Pandas para sumar una cantidad a cada celda de la Serie.
* `+ 2000000`: El operador matemático tradicional de Python. Hace exactamente lo mismo y es mucho más rápido de escribir.

In [7]:
nba["Salary"].add(50000)

0      18050000.0
1       1751593.0
2       1567981.0
3             NaN
4      16050000.0
          ...
493     4742840.0
494           NaN
495    41408814.0
496     8383333.0
497     3422840.0
Name: Salary, Length: 498, dtype: float64

In [8]:
nba["Salary"] + 2000000

0      20000000.0
1       3701593.0
2       3517981.0
3             NaN
4      18000000.0
          ...
493     6692840.0
494           NaN
495    43358814.0
496    10333333.0
497     5372840.0
Name: Salary, Length: 498, dtype: float64

# **5. Crear una nueva columna basada en operaciones**

No solo podemos calcular valores al aire, sino guardarlos permanentemente en la tabla:
* `nba["bonus_salary"] = ...`: Al combinar la asignación que vimos en clases pasadas con una suma matemática (`+ 30000`), creamos una columna completamente nueva que calcula automáticamente el bono para cada jugador.

In [9]:
nba["bonus_salary"] = nba["Salary"] + 30000
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country,bonus_salary
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS,18030000.0
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US,1731593.0
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO,1547981.0
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US,NaN
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH,16030000.0
...,...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP,4722840.0
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US,41388814.0
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US,8363333.0
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US,3402840.0

# **6. Operaciones de Resta**

De igual forma, podemos restar cantidades a toda la columna de manera masiva:
* `.sub(55000)`: El método formal de Pandas para restar un valor a cada registro.
* `#nba["Salary"] - sub(55000)`: El profesor deja este código comentado como ejemplo de un error común de sintaxis que debemos evitar.

In [10]:
nba["Salary"].sub(55000)
#nba["Salary"] - sub(55000)

0      17945000.0
1       1646593.0
2       1462981.0
3             NaN
4      15945000.0
          ...
493     4637840.0
494           NaN
495    41303814.0
496     8278333.0
497     3317840.0
Name: Salary, Length: 498, dtype: float64

#**7. Operaciones de División**

Útil para simplificar números grandes o convertir unidades:
* `.div(1000000)`: Divide cada salario de la columna entre un millón (ideal para simplificar reportes financieros).
* `/ 1000000`: Su equivalente usando el operador tradicional de barra diagonal, que cumple exactamente la misma función.

In [11]:
nba["Salary"].div(1000000)
#nba["Salary"]/1000000

0      18.000000
1       1.701593
2       1.517981
3            NaN
4      16.000000
         ...
493     4.692840
494          NaN
495    41.358814
496     8.333333
497     3.372840
Name: Salary, Length: 498, dtype: float64

# **8. Operaciones de Multiplicación (Conversión de unidades)**

Un uso práctico excelente de las matemáticas en Pandas es convertir sistemas de medida a nivel masivo:
* `.mul(0.453592)` o `* 0.453592`: Multiplica la columna de peso (`Weight`) por este factor constante para convertir masivamente las libras a kilogramos en toda la tabla en un solo paso.

In [12]:
nba["Weight"].mul(0.453592)
#nba["Weight"]*0.453592

0       99.790240
1       81.646560
2      108.862080
3       98.883056
4      108.862080
          ...
493    104.326160
494           NaN
495     90.718400
496    112.490816
497     97.522280
Name: Weight, Length: 498, dtype: float64

# **9. Resumen del proceso completo**

En conclusión, este archivo nos enseña el poder del cálculo vectorial (matemáticas masivas) en Pandas:
* **Adiós a los bucles o celdas manuales:** Comprendimos que Pandas aplica operaciones aritméticas a columnas enteras de manera simultánea, ahorrando miles de líneas de código.
* **Métodos vs. Operadores:** Descubrimos que tenemos dos caminos para operar datos: usar métodos formales (como `.add()` o `.div()`) o usar los operadores matemáticos tradicionales de Python (`+`, `-`, `/`, `*`).
* **Creación de valor:** Aprendimos a reciclar las operaciones matemáticas para alimentar columnas completamente nuevas (como el `bonus_salary`), lo que nos permite enriquecer nuestras bases de datos originales.