# **1. Conectar Google Drive a Colab (Mounting)**

Como regla indispensable para trabajar con archivos locales en Colab, preparamos nuestro entorno de trabajo:
* `from google.colab import drive`: Llamamos a la herramienta de conexión.
* `drive.mount('/content/drive')`: Autorizamos el acceso a nuestro almacenamiento en la nube para buscar el archivo CSV.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **2. Cargar los datos y optimizar tipos de datos desde la lectura**

Aplicamos una optimización avanzada al cargar nuestro archivo:
* `parse_dates = [...]`: Este parámetro especial dentro de `read_csv` le indica a Pandas que convierta automáticamente esas columnas en formato de fechas reales desde el mismo momento en que abre el archivo, ahorrándonos líneas de código posteriores.
* `astype(...)`: Convertimos las columnas categóricas y booleanas para optimizar el consumo de memoria RAM de la computadora.

In [3]:
import pandas as pd

insta = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/udmy/aplicada/Instagram.csv', parse_dates = ["reg date", "last login"])
insta["gender"] = insta["gender"].astype("category")
insta["Country"] = insta["Country"].astype("category")
insta["Influencer"] = insta["Influencer"].astype("bool")

insta.head()

,first name,last name,gender,reg date,last login,followers,posts,Influencer,Country
0,Corilla,Leuchars,Female,2011-02-11,2020-05-14 03:51:00,24536,462,False,Brazil
1,Forster,Gush,Male,2015-04-02,2020-07-11 07:41:00,8479,2581,True,United States
2,Everard,Jowers,Male,2018-11-14,2020-05-31 17:36:00,9356,6874,False,United Kingdom
3,Bob,Threader,Male,2019-06-13,2020-07-04 16:19:00,33319,3617,False,Australia
4,Deeann,Standell,Female,2011-04-26,2020-10-03 06:16:00,2908,98,False,NaN

# **3. Aplicar múltiples condiciones simultáneas (Operador AND)**

Si queremos filtrar filas que cumplan **todas** las reglas al mismo tiempo, usamos el operador ampersand (`&`), que representa la conjunción lógica "Y":
* `(Condición 1) & (Condición 2) & (Condición 3)`: Es una **regla de oro en Pandas** obligatoria: cada condición independiente debe ir obligatoriamente encerrada entre paréntesis `( )`. Si olvidas los paréntesis, Python se confundirá y arrojará un error matemático.
* En este ejemplo, filtramos usuarios que sean hombres (`"Male"`), cuya fecha de registro sea posterior al 31 de diciembre de 2015 (`> "2015-12-31"`), y que vivan en Estados Unidos (`"United States"`).

In [4]:
mask = (insta["gender"] == "Male") & (insta["reg date"] > "2015-12-31") & (insta["Country"] == "United States")
insta[mask]

,first name,last name,gender,reg date,last login,followers,posts,Influencer,Country
71,Cozmo,Garrold,Male,2017-09-27,2020-09-10 15:34:00,27795,2222,True,United States
187,Kyle,Filyukov,Male,2018-11-16,2020-10-24 05:15:00,26932,1165,False,United States
217,Terri,Fonte,Male,2017-09-03,2020-09-07 16:21:00,37839,1026,True,United States
343,Franz,Pavie,Male,2018-10-14,2020-09-21 05:01:00,1014,839,True,United States
367,Morten,Le Franc,Male,2019-08-20,2020-06-06 00:24:00,37124,2965,True,United States
455,Frankie,Davson,Male,2020-03-29,2020-08-06 09:56:00,11017,2206,True,United States
474,Jordan,Plews,Male,2017-08-31,2020-12-08 15:15:00,21143,7232,False,United States
523,Benito,Lumsdon,Male,2019-06-22,2020-06-01 14:53:00,27564,4803,False,United States
534,Bert,Woolvett,Male,2020-02-25,2020-12-20 20:13:00,11389,4729,False,United States
575,Tammie,Whiterod,Male,2020-08-04,2020-09-03 04:05:00,14145,4029,False,United States
587,Harald,Jewel,Male,2018-05-23,2020-05-20 10:18:00,17293,593,False,United States
614,Hilario,Worral,Male,2017-11-03,2020-08-13 14:28:00,14290,7443,True,United States
636,Currie,Bolger,Male,2016-05-11,2020-09-29 09:37:00,7896,6848,True,United States
642,Quinn,Minchinton,Male,2016-08-08,2020-05-16 01:23:00,17768,6006,False,United States
650,Ephrayim,Janovsky,Male,2019-10-14,2020-07-03 20:55:00,22896,3058,False,United States
656,Zelig,Nicholas,Male,2018-12-13,2020-11-05 00:26:00,5162,96,True,United States
670,Jorgan,Gooddy,Male,2016-09-15,2020-10-20 16:24:00,2921,7116,False,United States
684,Claus,Billett,Male,2017-04-29,2020-08-15 20:32:00,19587,1497,False,United States
690,Edgar,Lurner,Male,2018-12-24,2020-11-25 21:47:00,33582,2599,False,United States
732,Von,Stockall,Male,2019-05-04,2020-11-08 20:28:00,17113,1159,True,United States
771,Ariel,Grisedale,Male,2017-05-23,2020-11-15 21:58:00,33087,7171,False,United States
775,Raynard,Arendt,Male,2019-07-09,2020-12-07 18:37:00,20424,3154,False,United States
827,Xenos,Waples,Male,2018-10-15,2020-07-01 21:02:00,1963,5852,False,United States
850,Emmy,Craigg,Male,2020-02-22,2020-11-09 05:47:00,1069,3381,True,United States
872,Sollie,Van Niekerk,Male,2018-11-02,2020-12-21 02:40:00,24771,594,False,United States
911,Ricard,Thurlbeck,Male,2020-04-23,2020-11-29 06:01:00,22188,1145,False,United States
912,Xerxes,Sego,Male,2020-01-05,2020-10-08 01:40:00,29829,4894,True,United States
941,Guillermo,Slyman,Male,2019-10-09,2020-08-09 09:03:00,16808,1627,False,United States
963,Ruperto,Tuting,Male,2018-03-29,2020-09-08 21:07:00,24926,1913,False,United States

# **4. Organizar condiciones complejas usando variables (Máscaras múltiples)**

Cuando las consultas son muy largas, escribir todo en una sola línea puede volverse confuso de leer. Una excelente práctica profesional es dividir la lógica en partes:
* `mask1`, `mask2`, `mask3`: Guardamos cada regla de filtrado en una variable independiente.
* `insta[mask1 & mask2 & mask3]`: Al final, unimos todas las máscaras dentro de los corchetes usando el operador `&`. Esto hace que el código sea sumamente limpio, ordenado y fácil de depurar si algo falla.

In [5]:
mask1 = insta["gender"] == "Male"
mask2 = insta["reg date"] > "2015-12-31"
mask3 = insta["Country"] == "United States"
insta[mask1 & mask2 & mask3]

,first name,last name,gender,reg date,last login,followers,posts,Influencer,Country
71,Cozmo,Garrold,Male,2017-09-27,2020-09-10 15:34:00,27795,2222,True,United States
187,Kyle,Filyukov,Male,2018-11-16,2020-10-24 05:15:00,26932,1165,False,United States
217,Terri,Fonte,Male,2017-09-03,2020-09-07 16:21:00,37839,1026,True,United States
343,Franz,Pavie,Male,2018-10-14,2020-09-21 05:01:00,1014,839,True,United States
367,Morten,Le Franc,Male,2019-08-20,2020-06-06 00:24:00,37124,2965,True,United States
455,Frankie,Davson,Male,2020-03-29,2020-08-06 09:56:00,11017,2206,True,United States
474,Jordan,Plews,Male,2017-08-31,2020-12-08 15:15:00,21143,7232,False,United States
523,Benito,Lumsdon,Male,2019-06-22,2020-06-01 14:53:00,27564,4803,False,United States
534,Bert,Woolvett,Male,2020-02-25,2020-12-20 20:13:00,11389,4729,False,United States
575,Tammie,Whiterod,Male,2020-08-04,2020-09-03 04:05:00,14145,4029,False,United States
587,Harald,Jewel,Male,2018-05-23,2020-05-20 10:18:00,17293,593,False,United States
614,Hilario,Worral,Male,2017-11-03,2020-08-13 14:28:00,14290,7443,True,United States
636,Currie,Bolger,Male,2016-05-11,2020-09-29 09:37:00,7896,6848,True,United States
642,Quinn,Minchinton,Male,2016-08-08,2020-05-16 01:23:00,17768,6006,False,United States
650,Ephrayim,Janovsky,Male,2019-10-14,2020-07-03 20:55:00,22896,3058,False,United States
656,Zelig,Nicholas,Male,2018-12-13,2020-11-05 00:26:00,5162,96,True,United States
670,Jorgan,Gooddy,Male,2016-09-15,2020-10-20 16:24:00,2921,7116,False,United States
684,Claus,Billett,Male,2017-04-29,2020-08-15 20:32:00,19587,1497,False,United States
690,Edgar,Lurner,Male,2018-12-24,2020-11-25 21:47:00,33582,2599,False,United States
732,Von,Stockall,Male,2019-05-04,2020-11-08 20:28:00,17113,1159,True,United States
771,Ariel,Grisedale,Male,2017-05-23,2020-11-15 21:58:00,33087,7171,False,United States
775,Raynard,Arendt,Male,2019-07-09,2020-12-07 18:37:00,20424,3154,False,United States
827,Xenos,Waples,Male,2018-10-15,2020-07-01 21:02:00,1963,5852,False,United States
850,Emmy,Craigg,Male,2020-02-22,2020-11-09 05:47:00,1069,3381,True,United States
872,Sollie,Van Niekerk,Male,2018-11-02,2020-12-21 02:40:00,24771,594,False,United States
911,Ricard,Thurlbeck,Male,2020-04-23,2020-11-29 06:01:00,22188,1145,False,United States
912,Xerxes,Sego,Male,2020-01-05,2020-10-08 01:40:00,29829,4894,True,United States
941,Guillermo,Slyman,Male,2019-10-09,2020-08-09 09:03:00,16808,1627,False,United States
963,Ruperto,Tuting,Male,2018-03-29,2020-09-08 21:07:00,24926,1913,False,United States

# **5. Cuidado con las mayúsculas y minúsculas**

Un error común en programación es asumir que las palabras son iguales sin importar cómo se escriban:
* `(insta["gender"] == "male")`: Si escribimos la palabra en minúscula cuando en la base de datos está registrada con mayúscula inicial (`"Male"`), Pandas no encontrará ninguna coincidencia y nos devolverá una tabla completamente vacía. ¡Siempre debemos verificar el texto exacto!

In [6]:
mask = (insta["gender"] == "male") & (insta["reg date"] > "2015-12-31")
insta[mask]

Empty DataFrame
Columns: [first name, last name, gender, reg date, last login, followers, posts, Influencer, Country]
Index: []

# **6. Resumen del proceso completo**

En conclusión, este archivo nos enseña a realizar consultas avanzadas y reportes altamente específicos:
* **Carga optimizada:** Aprendimos a usar `parse_dates` directamente en la lectura para preparar las variables temporales de inmediato.
* **El operador AND (`&`):** Comprendimos cómo combinar múltiples requisitos lógicos para acotar nuestros resultados de búsqueda.
* **La regla de los paréntesis:** Memorizamos que al filtrar con varias condiciones en Pandas, cada bloque debe ir estrictamente entre paréntesis `( )` para evitar errores de sintaxis.
* **Legibilidad:** Valoramos el uso de múltiples máscaras (`mask1`, `mask2`) para estructurar código profesional, limpio y fácil de leer.