# ***1. Conectar Google Drive a Colab***

Como vamos a leer un archivo de Excel que está en nuestra cuenta, el primer paso es darle permisos a Colab para acceder a nuestro almacenamiento:
* `from google.colab import drive`: Llama a la herramienta de conexión.
* `drive.mount('/content/drive')`: Abre el puente de comunicación para poder buscar nuestro archivo de la NBA.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# ***2. Cargar la tabla de datos***

Como en todo análisis, el primer paso es abrir nuestro archivo para poder trabajar con él:
* `import pandas as pd`: Traemos nuestra librería de análisis.
* `read_excel()`: Cargamos el archivo local que contiene los datos de los equipos de la NBA.
* `.head()`: Imprimimos las primeras 5 filas para comprobar visualmente los nombres exactos de las columnas que vamos a utilizar.

In [ ]:
import pandas as pd
nba = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/udmy/Nba Teams.xlsx")
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH

# ***3. Extraer una columna específica (Método de corchetes)***

Para analizar una sola variable sin distraernos con el resto de la tabla, podemos "arrancar" una sola columna:
* `["Name"]`: Usamos el nombre de la variable de nuestra tabla (`nba`) seguido de corchetes y comillas. Adentro escribimos el nombre exacto de la columna. En este caso, nos traerá únicamente la lista con los nombres de los jugadores.

In [ ]:
nba["Name"]

0      Bogdan Bogdanovic
1        Brandon Goodwin
2         Bruno Fernando
3            Cam Reddish
4           Clint Capela
             ...
493        Rui Hachimura
494                  NaN
495    Russell Westbrook
496        Thomas Bryant
497       Troy Brown Jr.
Name: Name, Length: 498, dtype: object

# ***4. Extraer columnas numéricas***

Podemos aplicar exactamente la misma técnica para cualquier tipo de dato:
* `["Salary"]`: Al usar nuevamente los corchetes con el nombre exacto de la columna, extraemos ahora únicamente la información financiera (los salarios). Esta es la forma más segura de extraer datos en Pandas.

In [ ]:
nba["Salary"]

0      18000000.0
1       1701593.0
2       1517981.0
3             NaN
4      16000000.0
          ...
493     4692840.0
494           NaN
495    41358814.0
496     8333333.0
497     3372840.0
Name: Salary, Length: 498, dtype: float64

# ***5. Extraer una columna (Notación de punto)***

Existe una segunda forma de hacer exactamente lo mismo, que es más rápida para escribir:
* `.Name`: Usamos la variable de nuestra tabla (`nba`) seguida de un punto y el nombre de la columna, sin usar corchetes ni comillas. Hace exactamente lo mismo que `nba["Name"]`.
* **La regla de oro:** Este método rápido solo funciona si el nombre de la columna es una sola palabra. Si tuviera espacios (ejemplo: "First Name"), este método daría error y estaríamos obligados a usar los corchetes.

In [ ]:
nba.Name

0      Bogdan Bogdanovic
1        Brandon Goodwin
2         Bruno Fernando
3            Cam Reddish
4           Clint Capela
             ...
493        Rui Hachimura
494                  NaN
495    Russell Westbrook
496        Thomas Bryant
497       Troy Brown Jr.
Name: Name, Length: 498, dtype: object

# ***6. Resumen del proceso completo***

En conclusión, este archivo nos enseña a enfocarnos en variables específicas de nuestra base de datos:
* **Preparación:** Reforzamos que la conexión al Drive (Mounting) es el paso cero indispensable para leer archivos locales.
* **Enfoque analítico:** Aprendimos que podemos aislar columnas individuales (Series) para analizarlas por separado, sin cargar toda la tabla.
* **Dos caminos, un resultado:** Descubrimos los dos métodos de extracción: la *notación de corchetes* (`nba["Name"]`) y la *notación de punto* (`nba.Name`).
* **Seguridad vs. Rapidez:** Entendimos que aunque el método del punto es más rápido, el uso de corchetes es la práctica más segura a prueba de errores, especialmente si los nombres de las columnas contienen espacios.