# **1. Conectar Google Drive a Colab (Mounting**)

Como paso cero obligatorio para trabajar con archivos locales en Colab, preparamos el entorno:
* `from google.colab import drive`: Llamamos a la herramienta de conexión.
* `drive.mount('/content/drive')`: Autorizamos el acceso a nuestro almacenamiento en la nube para buscar el archivo de Excel.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **2. Cargar datos y ordenar por contenido (Values)**

Importamos nuestra librería y aplicamos un ordenamiento avanzado sobre las columnas:
* `import pandas as pd`: Llamamos a Pandas.
* `read_excel()`: Cargamos el archivo de la NBA desde la ruta exacta del Drive.
* `sort_values(["Team", "Name"])`: Ordena la tabla jerárquicamente primero por equipo y luego por nombre.
* `na_position = "first"`: Envía obligatoriamente todas las celdas vacías (`NaN`) al principio de la lista.
* `inplace = True`: Guarda esta reorganización de forma permanente en la tabla.

In [3]:
import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/aplicada/Nba Teams.xlsx')
nba.sort_values(["Team", "Name"], na_position = "first", inplace = True)
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
9,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
111,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
492,Robin Lopez,Washington Wizards,SouthEast,C,7'0,281.0,1988-04-01,Stanford,7300000.0,US
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

# **3. Ordenar por índice original (sort_index)**

Cuando aplicamos un ordenamiento por valores (como hicimos en el bloque anterior), los números de las filas (el índice del lado izquierdo) quedan completamente revueltos y salteados. Para solucionar esto usamos:
* `.sort_index()`: Esta herramienta inspecciona las etiquetas de las filas y devuelve la tabla a su orden numérico secuencial original (0, 1, 2, 3...), deshaciendo el caos que causó el filtro anterior o recuperando la estructura inicial de cuando cargamos el archivo.

In [4]:
nba.sort_index()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

# **4. Resumen del proceso completo**

En conclusión, este archivo nos enseña a manejar la anatomía y las etiquetas de las filas en Pandas:
* **El impacto del ordenamiento:** Comprendimos que al ordenar una tabla por sus valores, las etiquetas numéricas de las filas pierden su secuencia natural.
* **Restauración de la tabla:** Descubrimos `.sort_index()`, el método clave para restablecer el orden original basado en los índices, asegurando que podamos alternar entre vistas ordenadas por contenido y vistas ordenadas por posición cada vez que lo necesitemos.