# ***1. Crear una estructura de datos básica***

Para este archivo comenzaremos creando nuestra propia información desde cero:
* `import pandas as pd`: Traemos nuevamente nuestra herramienta principal de análisis.
* `numbers = [...]`: Creamos una lista básica de Python (un solo tren) que contiene una secuencia de números enteros.

In [1]:
import pandas as pd
numbers = [1, 2, 3, 4, 5, 6]

# ***2. Transformar una lista en un DataFrame***

Una lista normal se ve como una línea horizontal, pero podemos estructurarla mejor:
* `pd.DataFrame()`: Es la función principal de Pandas para crear tablas. Toma nuestra lista básica y la convierte en una tabla vertical de una sola columna, poniéndole índices numéricos automáticos a cada fila.

In [2]:
pd.DataFrame(numbers)

   0
0  1
1  2
2  3
3  4
4  5
5  6

# ***3. Crear datos estructurados (Lista de listas)***

Para simular una tabla real con varias filas y columnas, necesitamos una estructura más compleja:
* `data = [[...], [...]]`: Creamos una "lista de listas". Cada sub-lista (la que está adentro) representa una fila completa de información (en este caso, el nombre y la edad de una persona).

In [3]:
data = [["Jhon",  23], ["Mary", 18], ["Jhon", 31]]

# ***4. Transformar datos bidimensionales***

Ahora le entregamos esta estructura doble a Pandas para que haga la magia:
* `pd.DataFrame(data)`: Convierte nuestra lista de listas en una tabla visual. Como aún no le hemos dicho cómo se llaman las columnas, Pandas les asigna los números 0 y 1 por defecto.

In [4]:
pd.DataFrame(data)

      0   1
0  Jhon  23
1  Mary  18
2  Jhon  31

# ***5. Asignar nombres a las columnas***

Para que la tabla sea profesional y fácil de leer, debemos bautizar las columnas:
* `columns = [ ]`: Este parámetro dentro de la función nos permite pasarle una lista con textos. Así reemplazamos los números automáticos por los títulos reales: "name" (nombre) y "age" (edad).

In [5]:
pd.DataFrame(data, columns = ["name", "age"])

   name  age
0  Jhon   23
1  Mary   18
2  Jhon   31

# ***6. Asignar identificadores a las filas (Índices)***

Además de las columnas, también podemos cambiar el conteo automático del lado izquierdo:
* `index = [ ]`: Este parámetro nos permite asignarle un identificador único o "etiqueta" a cada fila. Aquí cambiamos el conteo (0, 1, 2) por códigos personalizados ("id1", "id2" y "id3").

In [7]:
pd.DataFrame(data, columns = ["name", "age"], index = ["id1", "id2", "id3"])

     name  age
id1  Jhon   23
id2  Mary   18
id3  Jhon   31

# ***7. Resumen del proceso completo***

En conclusión, este archivo demuestra cómo construir tablas de datos estructuradas manualmente:
* **Origen:** Comprendimos cómo organizar información usando listas básicas y listas anidadas (listas dentro de listas).
* **Conversión:** Utilizamos `pd.DataFrame()` como el molde maestro para convertir esas estructuras planas de Python en tablas manejables.
* **Personalización:** Aprendimos a utilizar los parámetros `columns` e `index` para etiquetar correctamente la información, un paso vital para que los datos sean comprensibles.