# ***1. Conectar Google Drive a Colab (Mounting)***

Como volveremos a leer nuestro archivo local de Excel, el paso cero siempre es conectar nuestro disco duro virtual:
* `from google.colab import drive`: Llama a la herramienta de conexión de Colab.
* `drive.mount('/content/drive')`: Abre el puente para que Python pueda buscar y leer nuestros archivos guardados en la nube.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# ***2. Cargar la tabla de datos***

Una vez conectados, preparamos nuestro espacio de trabajo:
* `import pandas as pd`: Traemos nuestra librería de análisis.
* `read_excel()`: Cargamos el archivo con los datos completos de la NBA.
* `.head()`: Imprimimos las primeras 5 filas para recordar los nombres exactos de nuestras columnas.

In [ ]:
import pandas as pd
nba = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/udmy/Nba Teams.xlsx")
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH

# ***3. Extraer múltiples columnas (Doble corchete)***

Para aislar más de una variable a la vez, ya no nos sirve el método del punto ni un solo corchete. Necesitamos usar **dobles corchetes**:
* `[[ ]]`: El primer par de corchetes (los de afuera) le indican a Pandas "voy a extraer algo". El segundo par (los de adentro) forman una **lista tradicional de Python** con los nombres de lo que queremos extraer.
* `["Name", "Team"]`: Al pasar esta lista, Pandas nos devuelve una "mini-tabla" que contiene únicamente la columna de nombres y la de equipos.

In [ ]:
nba[["Name", "Team"]]

                  Name                Team
0    Bogdan Bogdanovic       Atlanta Hawks
1      Brandon Goodwin       Atlanta Hawks
2       Bruno Fernando       Atlanta Hawks
3          Cam Reddish       Atlanta Hawks
4         Clint Capela       Atlanta Hawks
..                 ...                 ...
493      Rui Hachimura  Washington Wizards
494                NaN                 NaN
495  Russell Westbrook  Washington Wizards
496      Thomas Bryant  Washington Wizards
497     Troy Brown Jr.  Washington Wizards

[498 rows x 2 columns]

# ***4. Expandir nuestra tabla filtrada***

Podemos agregar tantas columnas como necesitemos dentro de nuestra lista interna, simplemente separándolas por comas:
* `[["Name", "Team", "Salary"]]`: Le pasamos una lista de tres elementos. El resultado es una tabla perfectamente limpia que excluye cualquier otra información (como el peso o la edad) y nos deja solo con los nombres, equipos y salarios.

In [ ]:
nba[["Name", "Team", "Salary"]]

                  Name                Team      Salary
0    Bogdan Bogdanovic       Atlanta Hawks  18000000.0
1      Brandon Goodwin       Atlanta Hawks   1701593.0
2       Bruno Fernando       Atlanta Hawks   1517981.0
3          Cam Reddish       Atlanta Hawks         NaN
4         Clint Capela       Atlanta Hawks  16000000.0
..                 ...                 ...         ...
493      Rui Hachimura  Washington Wizards   4692840.0
494                NaN                 NaN         NaN
495  Russell Westbrook  Washington Wizards  41358814.0
496      Thomas Bryant  Washington Wizards   8333333.0
497     Troy Brown Jr.  Washington Wizards   3372840.0

[498 rows x 3 columns]

# ***5. Resumen del proceso completo***

En conclusión, este archivo nos enseña a crear sub-tablas o vistas filtradas de nuestra información original:
* **La lógica del doble corchete `[[ ]]`:** Comprendimos que para extraer múltiples columnas no basta con escribir sus nombres, sino que debemos agruparlas dentro de una lista de Python (el corchete interior).
* **Evolución de la extracción:** En el archivo anterior vimos que al extraer una sola columna obtenemos una "Serie" (una lista simple). Ahora descubrimos que al extraer dos o más columnas, el resultado que obtenemos es un nuevo "DataFrame" (una tabla en miniatura), ideal para exportar o presentar informes enfocados en datos específicos.