#***1. Conectar Google Drive a Colab (Mounting)***

Nuestro paso cero obligatorio para trabajar con archivos locales:
* `from google.colab import drive`: Llamamos a la herramienta de conexión.
* `drive.mount('/content/drive')`: Autorizamos el acceso a nuestro disco duro virtual en la nube.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# ***2. Cargar la tabla de datos***

Preparamos nuestro entorno leyendo el archivo original:
* `read_excel()`: Buscamos el archivo de la NBA usando su ruta exacta (path).
* `.head(10)`: Imprimimos las primeras 10 filas para visualizar en dónde tenemos datos faltantes (que Pandas muestra como `NaN` - Not a Number).

In [2]:
import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/udmy/Nba Teams.xlsx')
nba.head(10)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
5,Danilo Gallinari,Atlanta Hawks,SouthEast,F,6'10,233.0,1988-08-08,NaN,19500000.0,IT
6,De'Andre Hunter,Atlanta Hawks,SouthEast,F,6'7,225.0,1997-12-02,Virginia,7422000.0,US
7,John Collins,Atlanta Hawks,SouthEast,F,6'9,235.0,1997-09-23,Wake Forest,4137302.0,US
8,Kevin Huerter,Atlanta Hawks,SouthEast,G,6'7,190.0,1998-08-27,Maryland,2761920.0,US
9,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

# ***3. Rellenar huecos en toda la tabla (Método global)***

En lugar de borrar las filas con datos faltantes, podemos rellenarlas con un valor por defecto:
* `.fillna(0)`: Esta herramienta busca absolutamente todas las celdas vacías (`NaN`) en la tabla y las reemplaza por un número cero.
* **El detalle clave:** Como no le pusimos el parámetro `inplace = True`, esto es solo un simulacro o vista previa. Nuestra tabla original no se ha modificado permanentemente.

In [3]:
nba.fillna(0)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18 00:00:00,0,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,0,180.0,1995-10-02 00:00:00,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15 00:00:00,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01 00:00:00,Duke,0.0,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18 00:00:00,0,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08 00:00:00,Gonzaga,4692840.0,JP
494,0,0,0,0,0,0.0,0,0,0.0,0
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12 00:00:00,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31 00:00:00,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28 00:00:00,Oregon,3372840.0,US

# ***4. Rellenar huecos quirúrgicamente (Numérico)***

Si rellenamos toda la tabla con ceros, podríamos arruinar columnas de texto. Lo ideal es rellenar columna por columna:
* `nba[["College"]]`: Primero, usamos el método de extracción (con doble corchete) para aislar únicamente la columna de las universidades.
* `.fillna(0, inplace = True)`: Le encadenamos la herramienta de relleno. Ahora, si un jugador no tiene universidad registrada, se le asignará un "0", y gracias al `inplace = True`, este parche sí queda guardado permanentemente.

In [4]:
nba[["College"]].fillna(0, inplace = True)
nba

/tmp/ipykernel_2341/3302740240.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nba[["College"]].fillna(0, inplace = True)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

# ***5. Rellenar huecos con etiquetas de texto***

El relleno no se limita a números. Si trabajamos con columnas de texto (como los nombres), podemos usar palabras:
* `nba["Name"]`: Extraemos la columna de nombres.
* `.fillna("Missing name", inplace = True)`: Si la base de datos olvidó registrar el nombre de un jugador, en lugar de poner un cero o dejarlo como `NaN`, el sistema escribirá automáticamente la frase "Missing name" (Nombre faltante), guardando el cambio para siempre.

In [5]:
nba["Name"].fillna("Missing name", inplace = True)
nba

/tmp/ipykernel_2341/586593885.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  nba["Name"].fillna("Missing name", inplace = True)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,Missing name,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

# ***6. Resumen del proceso completo***

En conclusión, este archivo nos da una alternativa menos destructiva para la limpieza de datos:
* **Conservación de información:** Aprendimos que `.fillna()` nos permite salvar filas que de otro modo tendríamos que borrar. Es como ponerle masilla a los huecos de nuestra base de datos.
* **Relleno global vs. específico:** Comprendimos que aplicar `.fillna()` a toda la tabla puede causar errores de formato (mezclar ceros numéricos en columnas de texto), por lo que la mejor práctica es aislar la columna que queremos reparar (ej. `nba["Name"]`).
* **Personalización de parches:** Comprobamos que podemos rellenar los datos vacíos tanto con valores numéricos (0) como con cadenas de texto ("Missing name"), adaptándonos a la naturaleza de cada columna.