# ***1. Conectar Google Drive a Colab (Mounting)***

Preparación obligatoria de nuestro entorno de trabajo:
* `from google.colab import drive`: Llamamos a la herramienta de conexión.
* `drive.mount('/content/drive')`: Autorizamos a Colab para que pueda entrar a nuestra cuenta y leer el archivo de Excel.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# ***2. Cargar la tabla de datos***

Importamos nuestra herramienta y cargamos la información original:
* `import pandas as pd`: Traemos a Pandas.
* `read_excel()`: Cargamos el archivo con los datos completos de los equipos.
* `.head()`: Visualizamos el encabezado para confirmar que tenemos todas las columnas originales (incluyendo "Salary").

In [2]:
import pandas as pd
nba = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/udmy/Nba Teams.xlsx")
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH

# ***3. Eliminar una columna (Visualización temporal)***

Usamos el método `.drop()` para borrar la columna de salarios:
* `.drop("Salary")`: Le indicamos que queremos deshacernos de la columna con ese nombre exacto.
* `axis = 1`: Le recordamos a Pandas que estamos apuntando a una columna (vertical).
* **El truco de esta línea:** Como no usamos el parámetro `inplace = True`, Pandas solo nos mostrará un "simulacro" o vista previa de cómo se vería la tabla sin esa columna, pero no modificará el archivo real.

In [3]:
nba.drop("Salary", axis = 1)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,CH
...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,US

# ***4. Comprobar que la tabla no ha cambiado***

Si llamamos de nuevo a nuestra tabla escribiendo simplemente su nombre, veremos la prueba de lo que explicamos arriba:
* Al imprimir `nba`, notaremos que la columna "Salary" sigue ahí intacta. Como fue un borrado temporal, la estructura original de nuestra memoria está a salvo.

In [4]:
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

# ***5. Eliminar permanentemente (Guardar cambios)***

Ahora sí aplicaremos la eliminación real:
* `inplace = True`: Al agregar este parámetro, le estamos dando la orden a Pandas de que "guarde los cambios". Ahora la destrucción de la columna "Salary" sí se aplica sobre nuestra tabla original de manera irreversible (dentro de esta sesión).

In [5]:
nba.drop("Salary", axis = 1, inplace = True)

# ***6. Borrado masivo (Eliminar varias columnas)***

Si necesitamos borrar mucha información de golpe, no hace falta escribir `.drop()` muchas veces:
* `["Team", "Division"]`: Al igual que cuando extraíamos columnas, si le entregamos a la herramienta una **lista de Python `[ ]`**, podemos pedirle que borre varias columnas simultáneamente.
* Con `axis = 1` confirmamos que son columnas y con `inplace = True` guardamos esta limpieza masiva de forma permanente.

In [6]:
nba.drop(["Team", "Division"], axis = 1, inplace = True)

# ***7. Resumen del proceso completo***

En conclusión, este archivo nos enseña el manejo seguro de la eliminación de datos, un paso crítico en cualquier limpieza de bases de datos:
* **Simulacros vs. Cambios Reales:** El aprendizaje más importante es el uso del parámetro `inplace = True`. Sin él, cualquier alteración que hagamos a la tabla será solo una vista previa temporal.
* **Manejo de Listas:** Reforzamos que en Pandas, siempre que queramos aplicar una acción (como extraer o borrar) a más de un elemento, debemos agrupar sus nombres dentro de una lista de Python `[ ]`.