# ***1. Conectar Google Drive a Colab (Mounting)***

Como siempre que vamos a leer archivos locales, nuestro paso cero es conectar nuestro disco duro virtual:
* `from google.colab import drive`: Llamamos a la herramienta de conexión.
* `drive.mount('/content/drive')`: Le damos los permisos a Colab para que encuentre nuestra carpeta.

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# ***2. Cargar la tabla y explorar sus extremos***

Una vez importados los datos, usamos herramientas para revisar tanto el principio como el final de la tabla:
* `read_excel()`: Cargamos nuestra base de datos indicando la ruta exacta (path) del archivo.
* `.head(10)`: A diferencia del `.head()` normal que muestra 5 filas, al ponerle un número entre los paréntesis le estamos indicando que nos muestre exactamente las primeras 10 filas.
* `.tail()`: Nos permite inspeccionar el final de la tabla para confirmar que se cargó completa.

In [5]:
import pandas as pd
nba = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/udmy/Nba Teams.xlsx")
nba.head(10)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
5,Danilo Gallinari,Atlanta Hawks,SouthEast,F,6'10,233.0,1988-08-08,NaN,19500000.0,IT
6,De'Andre Hunter,Atlanta Hawks,SouthEast,F,6'7,225.0,1997-12-02,Virginia,7422000.0,US
7,John Collins,Atlanta Hawks,SouthEast,F,6'9,235.0,1997-09-23,Wake Forest,4137302.0,US
8,Kevin Huerter,Atlanta Hawks,SouthEast,G,6'7,190.0,1998-08-27,Maryland,2761920.0,US
9,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [6]:
nba.tail()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

# ***3. Eliminar nulos y crear una nueva tabla***

La herramienta `.dropna()` funciona como una aspiradora: detecta cualquier fila que tenga un dato vacío y la elimina.
* `nbaNoNull = nba.dropna()`: En lugar de modificar nuestra tabla original, aplicamos la "aspiradora" y guardamos el resultado limpio dentro de una **nueva variable** llamada `nbaNoNull`. Así conservamos intacta la versión original por si la necesitamos después.

In [7]:
nbaNoNull = nba.dropna()
nbaNoNull

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
6,De'Andre Hunter,Atlanta Hawks,SouthEast,F,6'7,225.0,1997-12-02,Virginia,7422000.0,US
7,John Collins,Atlanta Hawks,SouthEast,F,6'9,235.0,1997-09-23,Wake Forest,4137302.0,US
8,Kevin Huerter,Atlanta Hawks,SouthEast,G,6'7,190.0,1998-08-27,Maryland,2761920.0,US
10,Kris Dunn,Atlanta Hawks,SouthEast,G,6'3,205.0,1994-03-18,Providence,4767000.0,US
...,...,...,...,...,...,...,...,...,...,...
492,Robin Lopez,Washington Wizards,SouthEast,C,7'0,281.0,1988-04-01,Stanford,7300000.0,US
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

# ***4. Simulacro de limpieza vs Guardado permanente***

Aquí reforzamos la lección más importante de Pandas sobre borrado de datos:
* `.dropna()`: Si lo ejecutamos solo, nos muestra una vista previa (simulacro) de cómo se vería la tabla limpia.
* `nba`: Al imprimir la tabla inmediatamente después, vemos que los datos vacíos siguen ahí.
* `#nba.dropna(inplace=True)`: El código inactivo demuestra que, al igual que con el método `.drop()`, necesitamos usar `inplace=True` si queremos que la "aspiradora" elimine los nulos permanentemente en la memoria.

In [8]:
#nba.dropna(inplace=True)
nba.dropna()
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

# ***5. Revisar el estado de la tabla***

Verificamos el estado técnico de nuestros datos en la memoria:
* `.info()`: Nos recuerda cuántas filas, columnas y datos válidos tenemos disponibles actualmente en la tabla original `nba`.

In [9]:
nba.info()
nba

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        484 non-null    object
 1   Team        484 non-null    object
 2   Division    484 non-null    object
 3   Position    484 non-null    object
 4   Height      470 non-null    object
 5   Weight      484 non-null    float64
 6   Birth_Date  484 non-null    datetime64[ns]
 7   College     422 non-null    object
 8   Salary      434 non-null    float64
 9   Country     484 non-null    object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 39.0+ KB

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

# ***6. Eliminar filas completamente vacías***

A veces no queremos borrar una fila si solo le falta un dato, sino únicamente cuando está totalmente en blanco:
* `how="all"`: Al agregar este parámetro dentro de la aspiradora `.dropna()`, le decimos a Pandas que sea más compasivo: "solo borra esta fila si **absolutamente todas** sus columnas están vacías".

In [10]:
nba.dropna(how="all")

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
492,Robin Lopez,Washington Wizards,SouthEast,C,7'0,281.0,1988-04-01,Stanford,7300000.0,US
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

# ***7. Decidir qué dirección limpiar (Ejes)***

Por defecto, la aspiradora borra filas (horizontal), pero podemos cambiar su comportamiento:
* `axis = 0`: Es el valor por defecto. Le indica a Pandas que elimine las **filas** enteras que contengan algún dato vacío.
* `axis = 1`: Cambia la dirección de limpieza a vertical. Le indica a Pandas que elimine **columnas completas** si detecta que falta al menos un solo dato en ellas. (Es una limpieza muy agresiva).

In [11]:
nba.dropna(axis = 0)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
6,De'Andre Hunter,Atlanta Hawks,SouthEast,F,6'7,225.0,1997-12-02,Virginia,7422000.0,US
7,John Collins,Atlanta Hawks,SouthEast,F,6'9,235.0,1997-09-23,Wake Forest,4137302.0,US
8,Kevin Huerter,Atlanta Hawks,SouthEast,G,6'7,190.0,1998-08-27,Maryland,2761920.0,US
10,Kris Dunn,Atlanta Hawks,SouthEast,G,6'3,205.0,1994-03-18,Providence,4767000.0,US
...,...,...,...,...,...,...,...,...,...,...
492,Robin Lopez,Washington Wizards,SouthEast,C,7'0,281.0,1988-04-01,Stanford,7300000.0,US
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

In [12]:
nba.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[498 rows x 0 columns]

# ***8. Limpieza enfocada en columnas clave***

Esta es la técnica más profesional. Nos permite dictar exactamente en dónde importa que falten datos:
* `subset = [ ]`: Le pasamos una lista de Python con nombres de columnas. Esto le dice a Pandas: "revisa únicamente las columnas Name, Salary y College. Si falta un dato en alguna de estas tres, borra la fila. Si el dato falta en otra columna diferente, ignóralo y no borres nada".

In [13]:
nba.dropna(subset = ["Name", "Salary", "College"])

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
6,De'Andre Hunter,Atlanta Hawks,SouthEast,F,6'7,225.0,1997-12-02,Virginia,7422000.0,US
7,John Collins,Atlanta Hawks,SouthEast,F,6'9,235.0,1997-09-23,Wake Forest,4137302.0,US
8,Kevin Huerter,Atlanta Hawks,SouthEast,G,6'7,190.0,1998-08-27,Maryland,2761920.0,US
...,...,...,...,...,...,...,...,...,...,...
492,Robin Lopez,Washington Wizards,SouthEast,C,7'0,281.0,1988-04-01,Stanford,7300000.0,US
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

# ***9. Resumen del proceso completo***

En conclusión, este archivo nos enseña el arsenal completo de herramientas para purificar nuestra base de datos manejando los valores nulos:
* **Seguridad de la información:** Aprendimos que en lugar de usar `inplace=True`, podemos guardar nuestra limpieza en una nueva variable (`nbaNoNull`) para proteger los datos originales.
* **Flexibilidad de limpieza:** Comprendimos cómo modificar el comportamiento estricto del borrado usando parámetros como `how="all"` (borrar solo filas 100% vacías) o `axis=1` (borrar columnas enteras en lugar de filas).
* **Limpieza inteligente:** Descubrimos que el parámetro `subset` nos permite realizar limpiezas quirúrgicas, salvando información valiosa al enfocar la "aspiradora" únicamente en las columnas que consideramos vitales para nuestro análisis.