# ***1. Conectar Google Drive a Colab (Mounting)***

Como regla general, siempre que vayamos a leer un archivo local, el primer paso es conectar nuestro disco duro virtual:
* `from google.colab import drive`: Llama a la herramienta de conexión de Colab.
* `drive.mount('/content/drive')`: Abre el puente para que Python pueda buscar nuestro archivo de Excel en la nube.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# ***2. Cargar la tabla de datos***

Preparamos nuestro espacio de trabajo importando las herramientas y los datos:
* `import pandas as pd`: Traemos nuestra librería de análisis.
* `read_excel()`: Cargamos el archivo completo.
* `.head()`: Imprimimos las primeras 5 filas para ver la tabla original antes de modificarla.

In [ ]:
import pandas as pd
nba = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/udmy/Nba Teams.xlsx")
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH

# ***3. Crear nuevas columnas (Asignación directa)***

En Pandas, si usamos corchetes con un nombre de columna que **no existe**, el programa crea esa columna automáticamente al final de la tabla.
* `nba["Teams"] = " "`: Crea una columna llamada "Teams" y rellena todas las filas con un espacio en blanco.
* `nba["nba Teams"] = " "`: Crea otra columna llamada "nba Teams" (con espacio en el nombre) y también la rellena con espacios.

In [ ]:
nba["Teams"] = " "
nba["nba Teams"] = " "
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country,Teams,nba Teams
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS,,
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US,,
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO,,
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US,,
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH,,

# ***4. Limitaciones del método del punto***

En este bloque, el profesor deja códigos comentados (inactivos) para demostrar errores comunes:
* `#nba.nba Teams`: Esto daría error. El método del punto se "rompe" porque el nombre de la columna tiene un espacio. Para estas columnas es obligatorio usar corchetes.
* `nba.Teams`: Esta línea sí funciona correctamente porque la columna "Teams" es una sola palabra sólida.

In [ ]:
#nba.Name
#nba.nba Teams
nba.Teams
#nba.Sports

0
1
2
3
4
      ..
493
494
495
496
497
Name: Teams, Length: 498, dtype: object

# ***5. Rellenar columnas con un valor fijo***

Aplicamos la misma lógica del Bloque 3, pero esta vez con texto real:
* `nba["Sports"] = "basket"`: Crea una nueva columna al final llamada "Sports" y le asigna la palabra "basket" a absolutamente todos los jugadores de la tabla.

In [ ]:
nba["Sports"] = "basket"
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country,Teams,nba Teams,Sports
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS,,,basket
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US,,,basket
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO,,,basket
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US,,,basket
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH,,,basket

# ***6. Eliminar columnas permanentemente (Método Drop)***

Si creamos una columna por error o ya no la necesitamos, usamos la herramienta de eliminación:
* `.drop("Teams")`: Busca la columna que se llama exactamente así para borrarla.
* `axis = 1`: Es una regla de Pandas. El "1" significa que vamos a borrar una columna (vertical). Si pusiéramos "0", borraría una fila (horizontal).
* `inplace = True`: Es el equivalente al botón de "Guardar cambios". Le dice a Pandas que aplique esta eliminación de forma permanente en nuestra tabla original.

In [ ]:
nba.drop("Teams", axis = 1, inplace = True)
#nba.insert(2, column = "Teams", value = "Colombians")
#nba.insert(2, column = "Sportss", value = "Turmequé")
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country,nba Teams,Sports
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS,,basket
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US,,basket
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO,,basket
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US,,basket
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH,,basket
...,...,...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP,,basket
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,,basket
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US,,basket
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US,,basket
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US,,basket

# ***7. Insertar columnas en posiciones exactas***

El método de corchetes que vimos arriba siempre pone las columnas nuevas al final de la tabla. Si queremos ponerla en medio, usamos esto:
* `.insert(2, ...)`: La herramienta de inserción nos pide primero la posición numérica. Como Python cuenta desde el 0 (0, 1, 2), el número `2` significa que la columna aparecerá en la tercera posición.
* `column = "Teams"`: Define el título que tendrá la nueva columna.
* `value = "Colombians"`: Define el texto con el que se van a rellenar todas las filas.

In [ ]:
nba.insert(2, column = "Teams", value = "Colombians")
nba

,Name,Team,Teams,Division,Position,Height,Weight,Birth_Date,College,Salary,Country,nba Teams,Sports
0,Bogdan Bogdanovic,Atlanta Hawks,Colombians,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS,,basket
1,Brandon Goodwin,Atlanta Hawks,Colombians,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US,,basket
2,Bruno Fernando,Atlanta Hawks,Colombians,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO,,basket
3,Cam Reddish,Atlanta Hawks,Colombians,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US,,basket
4,Clint Capela,Atlanta Hawks,Colombians,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH,,basket
...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,Colombians,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP,,basket
494,NaN,NaN,Colombians,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,,basket
495,Russell Westbrook,Washington Wizards,Colombians,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US,,basket
496,Thomas Bryant,Washington Wizards,Colombians,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US,,basket
497,Troy Brown Jr.,Washington Wizards,Colombians,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US,,basket

# ***8. Resumen del proceso completo***

En conclusión, este archivo nos enseña a ser arquitectos de nuestros propios DataFrames, modificando su estructura a voluntad:
* **Creación rápida:** Aprendimos a agregar columnas al final de la tabla usando la asignación directa por corchetes (`nba["Nueva"] = "Valor"`).
* **Posicionamiento exacto:** Descubrimos el método `.insert()`, que nos da control total sobre en qué posición específica (índice) queremos colocar nuestra nueva información.
* **Limpieza de datos:** Comprendimos cómo funciona el método `.drop()` para eliminar datos innecesarios, aplicando parámetros vitales como `axis = 1` (para especificar que es columna) e `inplace = True` (para guardar la destrucción de forma permanente).